[bondriver]
; BonDriver_LinuxDantto4k.so のログレベルを設定します。
; 0: none, 1: fatal, 2: error, 3: warning, 4: info, 5: debug, 6: verbose
logLevel=4

; ロードする BonDriver のパスを設定します。
; 絶対パスか BonDriver_LinuxDantto4k.so からの相対パスで指定します。
bondriverPath=/usr/local/lib/edcb/BonDriver_LinuxDVB.so
; BonDriverPath=BonDriver_LinuxDVB.so

; MMTS から TS への変換を行う BonDriver のチャンネル空間番号を設定します。
; コメントアウトし設定しない場合は、すべてのチャンネル空間で変換を行います。
; 設定した場合、指定したチャンネル空間のみ変換し、それ以外はパススルーです。
; BonDriver_LinuxDVB.ini であれば、チャンネル空間に Space=UHF,BS,BS4K,CS110 を
; 指定した場合、チャンネル空間番号は先頭をゼロとした記述順になります。
; UHF=0,BS=1,BS4K=2,CS110=3
; mmtsToTsChannelSpace=0,1
mmtsToTsChannelSpace=2

; [acas]
; casproxyserverを使用する場合はIPアドレスとポートをコロン区切りで設定します。
; casProxyServer=127.0.0.1:24000

; 使用するカードリーダー名を設定します。
; 複数のカードリーダーが接続されている場合、ACAS が接続されているカードリーダーを
; 特定するために指定します。
; smartCardReaderName=Alcor Link AK9563 00 00
